### ISSUE TITLE
Boost/Share button is work on progress?

### ISSUE THREAD

**Issue by hakaba-hitoyo** [NanaMorse/Cuckoo.Plus#124] opened 2019-02-27 07:29 UTC
This button seems to do nothing.

![image](https://user-images.githubusercontent.com/2155555/53473043-b95a4e80-3aac-11e9-853c-0a105905bca1.png)

**Comment by hakaba-hitoyo** [comment] 2019-02-27 07:52
`onReBlogMainStatus` seems not yet implemented.

https://github.com/NanaMorse/Cuckoo.Plus/blob/32d2e24276e9b887c9aa67f091ee5dbf28b61374/src/components/StatusCard/SimpleActionBar.vue#L70

**Comment by NanaMorse** [comment] 2019-02-27 08:04
oh, I almost forgot it...

**Comment by NanaMorse** [comment] 2019-02-27 08:09
Duplicate of #40

**Comment by NanaMorse** [comment] 2019-02-28 00:52
Resolved in #126

**Closed by NanaMorse** 2019-02-28 00:52 UTC
Labels: Doing
